.arm
/* this file contains some useful codes to pass to terminal stream so that we get
 * colored output and also allows us to get the current positions and such, which we need
 * for our pong game */

.ifndef A_OUTFORMAT_ASM
.equ	A_OUTFORMAT_ASM,		0x0

/* NOTE for some reason the macro doesnt work
 * when i include '\format\(): .ansiz \ansi_code\()',
 * when compiling its got trouble parsing it.*/

/* Creates a symbol which will contain the length
 * of each format
 * */
.macro A_OUTFORMAT_CREATE_FORMAT_END format
	\format\()_end:
	.equ	\format\()_LEN, \format\()_end - \format
.endm

.section .rodata

/* Base */
A_OUTFORMAT_ESC:                .asciz  "\x1b["
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_ESC

/* Reset */
A_OUTFORMAT_RESET_ALL:		.asciz	"\x1b[0m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_RESET_ALL

A_OUTFORMAT_RESET_BOLD:         .asciz  "\x1b[21m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_RESET_BOLD 

A_OUTFORMAT_RESET_DIM:          .asciz  "\x1b[22m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_RESET_DIM

A_OUTFORMAT_RESET_ITALIC:       .asciz  "\x1b[23m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_RESET_ITALIC

A_OUTFORMAT_RESET_UNDERLINE:    .asciz  "\x1b[24m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_RESET_UNDERLINE

A_OUTFORMAT_RESET_BLINK:        .asciz  "\x1b[25m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_RESET_BLINK

A_OUTFORMAT_RESET_REVERSE:      .asciz  "\x1b[27m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_RESET_REVERSE

A_OUTFORMAT_RESET_HIDDEN:       .asciz  "\x1b[28m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_RESET_HIDDEN

A_OUTFORMAT_RESET_STRIKETHROUGH:.asciz  "\x1b[29m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_RESET_STRIKETHROUGH

/* Text styles */
A_OUTFORMAT_STYLE_BOLD:         .asciz  "\x1b[1m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_STYLE_BOLD

A_OUTFORMAT_STYLE_DIM:          .asciz  "\x1b[2m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_STYLE_DIM

A_OUTFORMAT_STYLE_ITALIC:       .asciz  "\x1b[3m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_STYLE_ITALIC

A_OUTFORMAT_STYLE_UNDERLINE:    .asciz  "\x1b[4m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_STYLE_UNDERLINE

A_OUTFORMAT_STYLE_BLINK:        .asciz  "\x1b[5m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_STYLE_BLINK

A_OUTFORMAT_STYLE_BLINK_RAPID:  .asciz  "\x1b[6m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_STYLE_BLINK_RAPID

A_OUTFORMAT_STYLE_REVERSE:      .asciz  "\x1b[7m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_STYLE_REVERSE

A_OUTFORMAT_STYLE_HIDDEN:       .asciz  "\x1b[8m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_STYLE_HIDDEN

A_OUTFORMAT_STYLE_STRIKETHROUGH:.asciz  "\x1b[9m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_STYLE_STRIKETHROUGH

/* Standard foreground colors */
A_OUTFORMAT_COLOR_BLACK:        .asciz  "\x1b[30m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_COLOR_BLACK

A_OUTFORMAT_COLOR_RED:          .asciz  "\x1b[31m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_COLOR_RED

A_OUTFORMAT_COLOR_GREEN:        .asciz  "\x1b[32m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_COLOR_GREEN

A_OUTFORMAT_COLOR_YELLOW:       .asciz  "\x1b[33m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_COLOR_YELLOW

A_OUTFORMAT_COLOR_BLUE:         .asciz  "\x1b[34m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_COLOR_BLUE

A_OUTFORMAT_COLOR_MAGENTA:      .asciz  "\x1b[35m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_COLOR_MAGENTA

A_OUTFORMAT_COLOR_CYAN:         .asciz  "\x1b[36m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_COLOR_CYAN

A_OUTFORMAT_COLOR_WHITE:        .asciz  "\x1b[37m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_COLOR_WHITE

A_OUTFORMAT_COLOR_DEFAULT:      .asciz  "\x1b[39m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_COLOR_DEFAULT


/* Bright foreground colors */
A_OUTFORMAT_COLOR_BRIGHT_BLACK: .asciz  "\x1b[90m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_COLOR_BRIGHT_BLACK

A_OUTFORMAT_COLOR_BRIGHT_RED:   .asciz  "\x1b[91m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_COLOR_BRIGHT_RED

A_OUTFORMAT_COLOR_BRIGHT_GREEN: .asciz  "\x1b[92m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_COLOR_BRIGHT_GREEN

A_OUTFORMAT_COLOR_BRIGHT_YELLOW:.asciz  "\x1b[93m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_COLOR_BRIGHT_YELLOW

A_OUTFORMAT_COLOR_BRIGHT_BLUE:  .asciz  "\x1b[94m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_COLOR_BRIGHT_BLUE

A_OUTFORMAT_COLOR_BRIGHT_MAGENTA:.asciz "\x1b[95m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_COLOR_BRIGHT_MAGENTA

A_OUTFORMAT_COLOR_BRIGHT_CYAN:  .asciz  "\x1b[96m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_COLOR_BRIGHT_CYAN

A_OUTFORMAT_COLOR_BRIGHT_WHITE: .asciz  "\x1b[97m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_COLOR_BRIGHT_WHITE


/* Standard background colors */
A_OUTFORMAT_BACKGROUND_BLACK:   .asciz  "\x1b[40m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_BACKGROUND_BLACK

A_OUTFORMAT_BACKGROUND_RED:     .asciz  "\x1b[41m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_BACKGROUND_RED

A_OUTFORMAT_BACKGROUND_GREEN:   .asciz  "\x1b[42m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_BACKGROUND_GREEN

A_OUTFORMAT_BACKGROUND_YELLOW:  .asciz  "\x1b[43m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_BACKGROUND_YELLOW

A_OUTFORMAT_BACKGROUND_BLUE:    .asciz  "\x1b[44m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_BACKGROUND_BLUE

A_OUTFORMAT_BACKGROUND_MAGENTA: .asciz  "\x1b[45m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_BACKGROUND_MAGENTA

A_OUTFORMAT_BACKGROUND_CYAN:    .asciz  "\x1b[46m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_BACKGROUND_CYAN

A_OUTFORMAT_BACKGROUND_WHITE:   .asciz  "\x1b[47m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_BACKGROUND_WHITE

A_OUTFORMAT_BACKGROUND_DEFAULT: .asciz  "\x1b[49m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_BACKGROUND_DEFAULT


/* Bright background colors */
A_OUTFORMAT_BACKGROUND_BRIGHT_BLACK:   .asciz "\x1b[100m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_BACKGROUND_BRIGHT_BLACK

A_OUTFORMAT_BACKGROUND_BRIGHT_RED:     .asciz "\x1b[101m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_BACKGROUND_BRIGHT_RED

A_OUTFORMAT_BACKGROUND_BRIGHT_GREEN:   .asciz "\x1b[102m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_BACKGROUND_BRIGHT_GREEN

A_OUTFORMAT_BACKGROUND_BRIGHT_YELLOW:  .asciz "\x1b[103m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_BACKGROUND_BRIGHT_YELLOW

A_OUTFORMAT_BACKGROUND_BRIGHT_BLUE:    .asciz "\x1b[104m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_BACKGROUND_BRIGHT_BLUE

A_OUTFORMAT_BACKGROUND_BRIGHT_MAGENTA: .asciz "\x1b[105m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_BACKGROUND_BRIGHT_MAGENTA

A_OUTFORMAT_BACKGROUND_BRIGHT_CYAN:    .asciz "\x1b[106m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_BACKGROUND_BRIGHT_CYAN

A_OUTFORMAT_BACKGROUND_BRIGHT_WHITE:   .asciz "\x1b[107m"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_BACKGROUND_BRIGHT_WHITE


/* Cursor control */
A_OUTFORMAT_CURSOR_HOME:        .asciz  "\x1b[H"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_CURSOR_HOME

A_OUTFORMAT_CURSOR_SAVE:        .asciz  "\x1b[s"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_CURSOR_SAVE

A_OUTFORMAT_CURSOR_RESTORE:     .asciz  "\x1b[u"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_CURSOR_RESTORE


/* Screen control */
A_OUTFORMAT_CLEAR_SCREEN:       .asciz  "\x1b[2J"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_CLEAR_SCREEN

A_OUTFORMAT_CLEAR_LINE:         .asciz  "\x1b[2K"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_CLEAR_LINE

A_OUTFORMAT_CLEAR_LINE_RIGHT:   .asciz  "\x1b[K"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_CLEAR_LINE_RIGHT

A_OUTFORMAT_CLEAR_LINE_LEFT:    .asciz  "\x1b[1K"
A_OUTFORMAT_CREATE_FORMAT_END A_OUTFORMAT_CLEAR_LINE_LEFT

.endif /* A_OUTFORMAT_ASM */
